version: '3.9'

services:
  server:
    build:
      context: .
    container_name: 'schedule-focuser-backend'
    environment:
      NODE_ENV: production
      PORT: 3002
      DATABASE_URL: postgresql://psqluser:psqlpw@db:5432/psqlschedulerfocuser?schema=public
    ports:
      - 3002:3002
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: psqluser
      POSTGRES_PASSWORD: psqlpw
      POSTGRES_DB: psqlschedulerfocuser
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

