// Running the endpoints
// Ctrl + Shift + P -> Rest Client: Send Request
// Select a line and press F1 instead
###
GET http://localhost:3001/api/task HTTP/1.1
### - 204
GET http://localhost:3001/api/task/e6ab4459-8c67-419c-9396-c10278a237b2 HTTP/1.1
###
POST http://localhost:3001/api/task HTTP/1.1
Content-Type: application/json

{
    "title": "Lunch",
    "duration": "10AM - 11AM",
    "startTime": 1000,
    "endTime": 1100,
    "date": "2024-04-22T22:19:40.123Z"
}
###
###
PUT http://localhost:3001/api/task/8c071a22-1df2-4da0-a2fc-3a57abfc3d63 HTTP/1.1
Content-Type: application/json

{
    "title": "Lunch Time",
    "duration": "10AM - 11AM",
    "startTime": 1000,
    "endTime": 1100,
    "date": "2024-04-22T22:19:40.123Z"
}
###
###
DELETE http://localhost:3001/api/task/ede0d84a-fe68-4956-946f-3e8522f9acab HTTP/1.1
###